# Generated by Django 4.2.30 on 2026-04-18 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='actual_yield_kg',
            field=models.IntegerField(blank=True, help_text='Actual harvested yield in kg', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='area_hectares',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Field size in hectares', max_digits=8),
        ),
        migrations.AddField(
            model_name='field',
            name='avg_rainfall_mm',
            field=models.IntegerField(blank=True, help_text='Average monthly rainfall in mm', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='avg_temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='field',
            name='expected_harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='expected_yield_kg',
            field=models.IntegerField(blank=True, help_text='Expected yield in kg', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='location',
            field=models.CharField(blank=True, help_text='Field location/coordinates', max_length=255),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_nitrogen_ppm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_pH',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_phosphorus_ppm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='soil_potassium_ppm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='total_input_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total cost of inputs/fertilizers', max_digits=10),
        ),
        migrations.AddField(
            model_name='field',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
