# Generated by Django 4.2.30 on 2026-04-18 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fields', '0003_field_actual_yield_kg_field_area_hectares_and_more'),
        ('updates', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Fertilizer Application', 'Fertilizer Application'), ('Irrigation', 'Irrigation'), ('Pesticide/Herbicide', 'Pesticide/Herbicide'), ('Field Inspection', 'Field Inspection'), ('Harvest', 'Harvest'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.CharField(blank=True, help_text='e.g., 50kg, 100L, etc.', max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('logged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_date', models.DateTimeField(help_text='When the activity occurred')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='fields.field')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
    ]
